### ISSUE TITLE
Containerizeren SRAM-componenten

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#469]
Zie https://jira.ia.surf.nl/browse/SRAM-74

Doel is om SRAM helemaal te kunnen deployen in de nieuwe SURFconext Dockeromgeving.  Daarvoor moeten voor de losse SRAM-componenten container images worden gebouwd in de CI.  

Het gaat in eerste instantie over de basiscomponenten (sbs, meta, ldap).  De randzaken en beheerdingen (zabbix, demo-sp, etc) zijn (voor nu) buiten scope.

De generieke functionaliteit (os, nginx, apache, python, etc) moet komen in https://github.com/OpenConext/OpenConext-BaseContainers.  De SRAM-specifieke componenten bouwen daarbovenop hun eigen images, zoveel mogelijk in hun eigen repositories.

Dat betekent dus dat veel configuratie die nu nog in SRAM-deploy gebeurt, verplaatst wordt naar de images builds van de individuele componenten. Maar productiedeploys blijven (voor nu) zoals ze nu zijn, dus de container images zijn (voor nu) extra.

Daarvoor is nodig:
- [x] generieke container image voor python (https://github.com/SURFscz/OpenConext-BaseContainers/issues/1)
- [x] generieke container image voor apache2 (https://github.com/SURFscz/OpenConext-BaseContainers/issues/2)
- [x] container images(s) voor SBS (SURFscz/SBS#904)
- [x] container image voor openldap (see https://github.com/SURFscz/SRAM-containers/issues/1)
- [x] container image voor plsc (vervanging cron) (see https://github.com/SURFscz/plsc/issues/110)
- [x] container image voor metadata (statisch serveren) (see https://github.com/SURFscz/SRAM-containers/issues/2)
- [x] container image voor het genereren van metadata (vervanging cron) (see https://github.com/SURFscz/SRAM-containers/issues/3)
- [x] de VM setup moet containers gaan gebruiken ipv de container-as-VM hack.
